default:
   format: 'base64'
   algorithm: 'aes-128-cbc'
   private_key_file: './samples/keys/private_key.pem'
   public_key_file: './samples/keys/public_key.pub'

test:
   format: 'base64'
   algorithm: 'aes-128-cbc'
   private_key_file: './samples/keys/private_key.pem'
   public_key_file: './samples/keys/public_key.pub'

production:
   format: 'base64'
   algorithm: 'aes-128-cbc'
   private_key_file: './samples/keys/private_key.pem'
   public_key_file: './samples/keys/public_key.pub'
